### ISSUE TITLE
hmacValid function should output raw binary data

### ISSUE THREAD

**Issue by jpnut** [cronofy/cronofy-php#112]
Currently the `hmacValid` function does not function correctly, as the `hash_hmac` function call does not include `true` as the last parameter in order to set the output as binary.

https://github.com/cronofy/cronofy-php/blob/86e78475eb52d1839423bd8a3840ef8e6a8050fa/src/Cronofy.php#L1160

The example implementation [here](https://github.com/cronofy/notification-hmac-examples/blob/master/php/index.php) contains the binary flag and works as expected.

**Comment by ovgray** [comment]
This is still an issue!
