### ISSUE TITLE
Space in URL?

### ISSUE THREAD

**Issue by slavo2** [cronofy/cronofy-php#50]
Are we sure, that we want to separate scopes in `getAuthorizationURL` by literal spaces?

https://github.com/cronofy/cronofy-php/blob/master/cronofy.php#L233

While it might work in (some) web-browser, I suppose better practice would be to escape it.

https://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space

**Comment by slavo2** [comment]
Fix provided in https://github.com/cronofy/cronofy-php/pull/51

**Comment by stephenbinns** [comment]
fixed in `v0.17.6`
