### ISSUE TITLE
Missing Response Data

### ISSUE THREAD

**Issue by snake14** [cronofy/cronofy-php#59]
While using the request_token method, I noticed that most of the response JSON is discarded.  When I request an access token, using Postman, I receive the following values back: 

> {
    "access_token": "***masked***",
    "token_type": "bearer",
    "expires_in": 10800,
    "refresh_token": "***masked***",
    "scope": "create_event delete_event read_events",
    "sub": "***masked***",
    "account_id": "***masked***",
    "linking_profile": {
        "provider_name": "google",
        "profile_id": "***masked***",
        "profile_name": "***masked***"
    }
}

The Cronofy class only saves access_token, expires_in, and refresh_token.  Is that intentional?  I just think that some users, like myself, would like access to the other returned values.  It can be frustrating to read in the about available fields in the [API Docs](https://www.cronofy.com/developers/api/#token-issue-example-response) only to look through the PHP library code and find out that the library doesn't make them available.

**Comment by stephenbinns** [comment]
Hi @snake14 sorry about that, these fields are available to you via the following API calls

https://www.cronofy.com/developers/api/#userinfo
https://www.cronofy.com/developers/api/#profiles

I'm way about changing the return type of the request access token method as this may cause a breaking change for our existing users. Would introducing a new method which returns the full type be useful to you?

**Comment by snake14** [comment]
Stephen,
     Yeah, I ended up making the userinfo and profiles API calls to get the data that I needed, but it's inefficient to make two additional API calls for data that has already been returned by the token API call.  I totally understand not wanting to break existing functionality.  A separate method that returns the full response would be great.  I was going to try doing it myself, but the Cronofy->http_post method is private.  In fact, it looks like all you would need to do is copy the Cronofy->request_token method and return $tokens instead of true when the response is successful.  I would greatly appreciate it, if someone could do that.

Thanks,
Jacob
On Aug 17, 2018, 6:28 AM -0700, Stephen Binns <notifications@github.com>, wrote:

Hi @snake14<https://github.com/snake14> sorry about that, these fields are available to you via the following API calls

https://www.cronofy.com/developers/api/#userinfo
https://www.cronofy.com/developers/api/#profiles

I'm way about changing the return type of the request access token method as this may cause a breaking change for our existing users. Would introducing a new method which returns the full type be useful to you?
