### ISSUE TITLE
Question - where is the notification payload documentation?

### ISSUE THREAD

**Issue by mkarnicki** [cronofy/cronofy-php#78]
Hi, I was reviewing Cronofy notification channels to listen for events. I can't find where the actual notification/webhook payload is documented. Could you please point me at it or, if not documented, provide the expected payload format? Thanks!

**Comment by gshutler** [comment]
https://docs.cronofy.com/developers/api/push-notifications/ includes an example of a notification request you'll receive and so on.

If you've got further questions feel free to email us at support@cronofy.com

**Comment by mkarnicki** [comment]
Hi Garry :) I read this documentation page multiple times (also asked a colleague to help find the payload). Unfortunately, if you look closely, the notification payload (the one from the callback) is not documented. There's request and response when creating a notification channel, for instance, but there's nothing about the notification/webhook payload. Or am I just being blind :D?
