### ISSUE TITLE
Batch endpoint support

### ISSUE THREAD

**Issue by Jack97** [cronofy/cronofy-php#95]
Hi Guys,

It doesn't look like the batch endpoint has been exposed by the PHP client.

I can see that it exists in the Ruby client - my question is, would you be receptive to a PR if I modelled the functionality around the Ruby client's implementation?

Cheers,
Jack

**Comment by AdamWhittingham** [comment]
Hi Jack,

If you are comfortable adding support, then a PRs to add it would be very welcome!

**Comment by AdamWhittingham** [comment]
Hi @Jack97

Thanks again for your contribution! It is now released as part of [V1.2.0](https://packagist.org/packages/cronofy/cronofy)

**Comment by Jack97** [comment]
Brilliant, thanks for getting that merged @AdamWhittingham! I'll definitely be in touch for the stickers!
